version: "3.9"

services:
  docker-gui:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: docker-gui
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - docker-gui-data:/app/data
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      DOCKER_HOST: ${DOCKER_HOST:-unix:///var/run/docker.sock}
      DATABASE_URL: file:/app/data/docker-gui.db
      JWT_SECRET: ${JWT_SECRET:-change-me-in-production}
      DEFAULT_ADMIN_EMAIL: ${DEFAULT_ADMIN_EMAIL:-admin@example.com}
      DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD:-}
      DEFAULT_ADMIN_NAME: ${DEFAULT_ADMIN_NAME:-Super Administrator}
      AUTH_COOKIE_SECURE: ${AUTH_COOKIE_SECURE:-false}
      SYSTEM_METRICS_PROVIDER: ${SYSTEM_METRICS_PROVIDER:-docker}
    restart: unless-stopped
    networks:
      - docker-gui-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  docker-gui-data:
    driver: local

networks:
  docker-gui-network:
    driver: bridge
