version: '3.8'

services:
  docker-gui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-gui
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - docker-gui-data:/app/data
    environment:
      - NODE_ENV=production
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATABASE_URL=file:/app/data/docker-gui.db
      - JWT_SECRET=${JWT_SECRET:-change-me-in-production}
    restart: unless-stopped
    networks:
      - docker-gui-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  docker-gui-data:
    driver: local

networks:
  docker-gui-network:
    driver: bridge

