version: "3.9"

services:
  docker-gui:
    container_name: docker-gui-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: sh -c "yarn install && yarn db:migrate && yarn db:seed && yarn dev"
    environment:
      NODE_ENV: development
      PORT: 3000
      HOSTNAME: 0.0.0.0
      DOCKER_HOST: ${DOCKER_HOST:-unix:///var/run/docker.sock}
      DATABASE_URL: file:/app/data/docker-gui.db
      JWT_SECRET: ${JWT_SECRET:-change-me-in-development}
      NEXT_PUBLIC_USE_MOCKS: ${NEXT_PUBLIC_USE_MOCKS:-false}
      DEFAULT_ADMIN_EMAIL: ${DEFAULT_ADMIN_EMAIL:-admin@example.com}
      DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD:-}
      DEFAULT_ADMIN_NAME: ${DEFAULT_ADMIN_NAME:-Super Administrator}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - docker-gui-node-modules:/app/node_modules
      - docker-gui-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker-gui-network

volumes:
  docker-gui-node-modules:
  docker-gui-data:

networks:
  docker-gui-network:
    driver: bridge
