#!/usr/bin/env bash
#
# docker-gui installer
#
# Usage (from a fresh Linux server):
#   curl -fsSL https://get.docker-gui.io/install.sh | sudo bash
#
# Or, from a local checkout:
#   sudo ./scripts/install.sh
#
# Idempotent: re-running upgrades the existing install. Existing data and
# secrets are preserved.

set -euo pipefail

# ---------- config ----------

INSTALL_DIR="${DOCKER_GUI_DIR:-/opt/docker-gui}"
REPO="${DOCKER_GUI_REPO:-https://github.com/anthropics/docker-gui.git}"
BRANCH="${DOCKER_GUI_BRANCH:-main}"
WEB_PORT="${DOCKER_GUI_WEB_PORT:-3000}"

# ---------- helpers ----------

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
ok()   { printf '  \033[0;32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[0;33m⚠\033[0m %s\n' "$*"; }
err()  { printf '  \033[0;31m✗\033[0m %s\n' "$*" >&2; }

require_root() {
  if [[ $EUID -ne 0 ]]; then
    err "This script must run as root (sudo)."
    exit 1
  fi
}

detect_os() {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "macos"
  elif [[ -f /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    echo "${ID:-linux}"
  else
    echo "unknown"
  fi
}

# ---------- pre-flight checks ----------

OS="$(detect_os)"
log "Detected OS: $OS"

if [[ "$OS" == "macos" ]]; then
  warn "macOS detected. Production install via this script is not supported on macOS."
  warn "For local dev on Mac, see docs/DEVELOPMENT.md instead."
  exit 1
fi

require_root

# ---------- Docker ----------

log "Checking Docker"
if ! command -v docker >/dev/null 2>&1; then
  warn "Docker not found. Installing via get.docker.com..."
  curl -fsSL https://get.docker.com | sh
  ok "Docker installed"
else
  ok "Docker present ($(docker --version | head -1))"
fi

if ! docker info >/dev/null 2>&1; then
  warn "Docker daemon not running. Starting..."
  systemctl enable docker
  systemctl start docker
fi

if ! docker compose version >/dev/null 2>&1; then
  err "Docker Compose plugin not available. Install docker-compose-plugin and retry."
  exit 1
fi
ok "Docker daemon reachable"

# ---------- ports ----------

log "Checking ports"
if ss -tnlp 2>/dev/null | awk '{print $4}' | grep -q ":${WEB_PORT}\$"; then
  err "Port $WEB_PORT is already in use. Set DOCKER_GUI_WEB_PORT to a free port."
  exit 1
fi
ok "Port $WEB_PORT is free"

# ---------- repo ----------

log "Setting up $INSTALL_DIR"
if [[ ! -d "$INSTALL_DIR" ]]; then
  mkdir -p "$INSTALL_DIR"
fi
cd "$INSTALL_DIR"

if [[ -d .git ]]; then
  ok "Existing checkout found — updating"
  git fetch --depth=1 origin "$BRANCH"
  git reset --hard "origin/$BRANCH"
else
  ok "Cloning $REPO ($BRANCH)"
  git clone --depth=1 --branch "$BRANCH" "$REPO" .
fi

# ---------- secrets ----------

log "Configuring secrets"
if [[ ! -f .env ]]; then
  JWT_SECRET="$(openssl rand -hex 32)"
  SETUP_SECRET="$(openssl rand -hex 32)"
  cat > .env <<EOF
# Generated by install.sh on $(date -Iseconds)
JWT_SECRET=$JWT_SECRET
SETUP_SECRET=$SETUP_SECRET
WEB_PORT=$WEB_PORT
EOF
  chmod 600 .env
  ok "Generated .env (mode 600)"
else
  ok "Existing .env preserved"
fi

# ---------- build + start ----------

log "Building images (this can take a few minutes)"
docker compose build

log "Starting stack"
docker compose up -d

# ---------- wait for ready ----------

log "Waiting for service health"
ATTEMPTS=60
for i in $(seq 1 $ATTEMPTS); do
  if curl -fsS "http://127.0.0.1:${WEB_PORT}/api/v1/health/live" >/dev/null 2>&1; then
    ok "Service ready (took ${i}s of ${ATTEMPTS}s budget)"
    READY=1
    break
  fi
  sleep 1
done

if [[ "${READY:-0}" != "1" ]]; then
  err "Service did not become healthy within ${ATTEMPTS} seconds."
  err "Run: docker compose -f $INSTALL_DIR/docker-compose.yml logs"
  exit 1
fi

# ---------- finish ----------

SETUP_SECRET="$(grep '^SETUP_SECRET=' "$INSTALL_DIR/.env" | cut -d= -f2)"
HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
[[ -z "${HOST_IP:-}" ]] && HOST_IP="<your-server-ip>"

cat <<EOF

\033[1;32m================================================================\033[0m
  docker-gui is running

  URL:           http://${HOST_IP}:${WEB_PORT}
  Setup secret:  ${SETUP_SECRET}
                 (use this once on the login page to create the first admin)

  Health check:  ${INSTALL_DIR}/scripts/doctor.sh
  Logs:          docker compose -f ${INSTALL_DIR}/docker-compose.yml logs -f
  Update:        sudo ${INSTALL_DIR}/scripts/install.sh
  Uninstall:     sudo ${INSTALL_DIR}/scripts/uninstall.sh
\033[1;32m================================================================\033[0m

EOF
